[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Redirect old book URLs to the new slug-based URLs via a function
[[redirects]]
  from = "/book/:id"
  to = "/.netlify/functions/redirect-book?id=:id"
  status = 301 # Permanent Redirect
  force = true # Ensure this runs even if a file exists at /book/:id (unlikely but safe)

# Redirect old multimedia URLs to the new slug-based URLs via a function
[[redirects]]
  from = "/multimedia/:id"
  to = "/.netlify/functions/redirect-multimedia?id=:id"
  status = 301 # Permanent Redirect
  force = true

# SPA fallback rule (must come AFTER specific redirects)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Note: The actual API keys should be set in the Netlify dashboard
# This is just a placeholder to indicate that the variables are needed
[template.environment]
  RESEND_API_KEY = "your_resend_api_key"
  SUPABASE_URL = "your_supabase_url"
  SUPABASE_SERVICE_ROLE_KEY = "your_supabase_service_role_key"
  MAILERLITE_API_KEY = "your_mailerlite_api_key"
